### ISSUE TITLE
Tracking 

### ISSUE THREAD

**Issue by ratulalahy** [ratulalahy/process_property_linkage#1]
Incorporate experiment tracking with WandB or 

- [ ] track and visualize loss function.
- [ ] track and visualize other performance measures of a model.
- [ ] track and log model parameters

- [ ] track performance for various models
